const EARTH_RADIUS_KM = 6371.0088;
const RADIUS_KM = 0.5;
export const WEIGHTS = Object.freeze({ water: 25, forest: 20, viewpoint: 30, park: 15, nature_reserve: 25, industrial: -20, highway: -15 });
const DETAIL_KEYS = ["water", "forest", "viewpoint", "park", "nature_reserve", "negative"];

function coordinate(value) {
  if (Array.isArray(value)) return Number.isFinite(Number(value[0])) && Number.isFinite(Number(value[1])) ? { lon: Number(value[0]), lat: Number(value[1]) } : null;
  const lat = Number(value?.lat ?? value?.latitude), lon = Number(value?.lon ?? value?.lng ?? value?.longitude);
  return Number.isFinite(lat) && Number.isFinite(lon) ? { lat, lon } : null;
}
export function routePoints(route) {
  const geometry = route?.geometry;
  if (geometry?.type === "LineString") return geometry.coordinates.map(coordinate).filter(Boolean);
  if (Array.isArray(geometry)) return geometry.map(coordinate).filter(Boolean);
  if (geometry?.geometry) return routePoints(geometry);
  return (route?.points || []).map(coordinate).filter(Boolean);
}
function haversine(a, b) { const rad = Math.PI / 180, dLat = (b.lat - a.lat) * rad, dLon = (b.lon - a.lon) * rad, h = Math.sin(dLat / 2) ** 2 + Math.cos(a.lat * rad) * Math.cos(b.lat * rad) * Math.sin(dLon / 2) ** 2; return EARTH_RADIUS_KM * 2 * Math.atan2(Math.sqrt(h), Math.sqrt(Math.max(0, 1 - h))); }
export function routeDistanceKm(points) { let total = 0; for (let i = 1; i < points.length; i += 1) total += haversine(points[i - 1], points[i]); return total; }
function segmentDistanceKm(point, a, b) { const rad = Math.PI / 180, scale = 111.32 * Math.cos(point.lat * rad), px = (point.lon - a.lon) * scale, py = (point.lat - a.lat) * 111.32, bx = (b.lon - a.lon) * scale, by = (b.lat - a.lat) * 111.32, denominator = bx * bx + by * by, ratio = denominator ? Math.max(0, Math.min(1, (px * bx + py * by) / denominator)) : 0; return Math.hypot(px - ratio * bx, py - ratio * by); }
function pointInPolygon(point, ring) { let inside = false; for (let i = 0, j = ring.length - 1; i < ring.length; j = i += 1) { const xi = ring[i].lon, yi = ring[i].lat, xj = ring[j].lon, yj = ring[j].lat, intersects = ((yi > point.lat) !== (yj > point.lat)) && point.lon < ((xj - xi) * (point.lat - yi)) / ((yj - yi) || Number.EPSILON) + xi; if (intersects) inside = !inside; } return inside; }
function featureCoordinates(feature) { const geometry = feature?.geometry; if (Array.isArray(geometry)) return geometry.map(coordinate).filter(Boolean); if (geometry?.type === "LineString") return geometry.coordinates.map(coordinate).filter(Boolean); if (geometry?.type === "Polygon") return geometry.coordinates.flat().map(coordinate).filter(Boolean); if (geometry?.type === "MultiPolygon") return geometry.coordinates.flat(2).map(coordinate).filter(Boolean); return [coordinate(feature), coordinate(feature?.center)].filter(Boolean); }
export function nearestDistanceKm(points, feature) { if (points.length < 1) return Infinity; const candidates = featureCoordinates(feature); let best = Infinity; for (const candidate of candidates) { best = Math.min(best, haversine(candidate, points[0])); for (let i = 1; i < points.length; i += 1) best = Math.min(best, segmentDistanceKm(candidate, points[i - 1], points[i])); } const geometry = feature?.geometry; const ring = Array.isArray(geometry) && geometry.length > 3 ? geometry.map(coordinate).filter(Boolean) : geometry?.type === "Polygon" ? geometry.coordinates[0].map(coordinate).filter(Boolean) : null; if (ring?.length > 3 && points.some((point) => pointInPolygon(point, ring))) return 0; return best; }
function category(tags = {}) { const natural = String(tags.natural || "").toLowerCase(), leisure = String(tags.leisure || "").toLowerCase(), tourism = String(tags.tourism || "").toLowerCase(), landuse = String(tags.landuse || "").toLowerCase(), highway = String(tags.highway || "").toLowerCase(); if (["motorway", "trunk"].includes(highway)) return "highway"; if (["industrial", "quarry"].includes(landuse) || tags.industrial != null) return "industrial"; if (tourism === "viewpoint") return "viewpoint"; if (leisure === "nature_reserve" || String(tags.boundary || "").toLowerCase() === "protected_area") return "nature_reserve"; if (["park", "garden"].includes(leisure)) return "park"; if (["wood", "forest", "heath", "scrub"].includes(natural) || landuse === "forest") return "forest"; if (["water", "wetland", "beach", "spring", "riverbank"].includes(natural) || tags.waterway != null || tags.water != null) return "water"; return null; }
function emptyResult(status = "unavailable", dataSource = "none") { return { score: null, details: Object.fromEntries(DETAIL_KEYS.map((key) => [key, 0])), features: [], status, counts: { water: 0, forest: 0, viewpoint: 0, park: 0, nature_reserve: 0, industrial: 0, highway: 0 }, dataSource }; }
export function calculateScenicScore(route, osmData) { if (arguments.length < 2 || osmData === undefined) return import("../api/osm.js").then(({ queryRouteAmenities }) => queryRouteAmenities(route).then((data) => calculateScenicScore(route, data))); const points = routePoints(route); if (points.length < 2) return emptyResult(); if (osmData.status === "offline" || osmData.status === "unavailable") return emptyResult(osmData.status, osmData.dataSource); const features = Array.isArray(osmData) ? osmData : (osmData.features || osmData.elements || osmData.data || []); const counts = { water: 0, forest: 0, viewpoint: 0, park: 0, nature_reserve: 0, industrial: 0, highway: 0 }, matched = [], seen = new Set(); for (const feature of features) { const key = feature?.id == null ? null : `${feature.type || "nwr"}:${feature.id}`; if (key && seen.has(key)) continue; if (key) seen.add(key); const kind = category(feature?.tags || {}); if (!kind || nearestDistanceKm(points, feature) > RADIUS_KM) continue; counts[kind] += 1; matched.push({ feature, kind }); } const distanceKm = Math.max(0.1, Number(route.distanceKm) || routeDistanceKm(points)), details = Object.fromEntries(DETAIL_KEYS.map((key) => [key, 0])); for (const [kind, weight] of Object.entries(WEIGHTS)) { const contribution = weight * Math.min(1, counts[kind] / (distanceKm / 10)); details[["industrial", "highway"].includes(kind) ? "negative" : kind] += Number(contribution.toFixed(2)); } const labels = { water: "湖边骑行", forest: "林间道路", viewpoint: "观景点", park: "公园绿地", nature_reserve: "自然保护区", industrial: "工业区域", highway: "高速附近" }; return { score: Math.max(0, Math.min(100, Math.round(Object.values(details).reduce((sum, value) => sum + value, 0)))), details, features: matched.map(({ kind }) => labels[kind]), matchedFeatures: matched.map(({ feature }) => feature), status: osmData.status === "partial" ? "partial" : "ready", counts, dataSource: osmData.dataSource || "overpass" }; }
export { category };
