import { fetchJson, getConfig } from "./http.js";

const POSITIVE = ['[natural~"water|wood|forest|heath|scrub|beach|wetland|spring|cliff|peak"]', '[tourism~"viewpoint|attraction|picnic_site"]', '[leisure~"park|nature_reserve"]', '[boundary="protected_area"]', '[landuse="forest"]', '[waterway]'];
const NEGATIVE = ['[landuse~"industrial|quarry"]', '[industrial]', '[highway~"motorway|trunk"]'];
const SUPPLY = ['[amenity~"cafe|restaurant|fuel"]', '[shop~"convenience|supermarket"]'];
const num = (v) => Number.isFinite(+v) ? +v : null;
export function routeCoordinates(route) { if (Array.isArray(route)) return route.map((p) => Array.isArray(p) ? p : [p.lon ?? p.lng, p.lat]).filter((p) => num(p[0]) != null && num(p[1]) != null); const g = route?.geometry; if (g?.type === "LineString") return routeCoordinates(g.coordinates); if (Array.isArray(g)) return routeCoordinates(g); if (g?.geometry) return routeCoordinates(g); return (route?.points || []).map((p) => [p.lon ?? p.lng, p.lat]).filter((p) => num(p[0]) != null && num(p[1]) != null); }
export function safeTags(tags) { const out = {}; for (const [k, v] of Object.entries(tags || {})) if (["string", "number", "boolean"].includes(typeof v)) out[String(k)] = v; return out; }
function safeElement(e) { const tags = safeTags(e?.tags); let lat = num(e?.lat ?? e?.center?.lat), lon = num(e?.lon ?? e?.center?.lon); const out = { id: e?.id, type: e?.type, tags }; if (lat != null) out.lat = lat; if (lon != null) out.lon = lon; if (e?.geometry) out.geometry = e.geometry.slice(0, 5000); if (e?.nodes) out.nodes = e.nodes.slice(0, 2000); return out; }
function hav(a, b) { const p = Math.PI / 180, x = (b[0] - a[0]) * p * 6371 * Math.cos((a[1] + b[1]) * p / 2), y = (b[1] - a[1]) * p * 6371; return Math.hypot(x, y); }
function corridor(coords, max = 0.6) { const out = []; let total = 0; for (let i = 1; i < coords.length; i++) { const a = coords[i - 1], b = coords[i]; total += hav(a, b); if (total > 600) return []; const n = Math.max(1, Math.ceil(hav(a, b) / max)); for (let j = 0; j < n; j++) out.push([a[0] + (b[0] - a[0]) * j / n, a[1] + (b[1] - a[1]) * j / n]); } if (coords.length) out.push(coords.at(-1)); return out; }
function chunks(a, n) { const out = []; for (let i = 0; i < a.length; i += n) out.push(a.slice(i, i + n)); return out; }
function query(points, supplies = false) { const clauses = []; for (const [lon, lat] of points) for (const f of [...POSITIVE, ...NEGATIVE, ...(supplies ? SUPPLY : [])]) clauses.push(`nwr(around:500,${lat},${lon})${f}`); return `[out:json][timeout:25];(${clauses.join(";")};);out center geom tags;`; }
function statusFor(error, signal) { if (signal?.aborted) throw error; return "unavailable"; }
function normalize(payload, status = "ready") { const seen = new Set(), features = []; for (const e of payload?.elements || []) { const x = safeElement(e), key = `${x.type}:${x.id}`; if (x.id != null && !seen.has(key)) { seen.add(key); features.push(x); } } return { status, features, elements: features, data: features, counts: { total: features.length }, dataSource: "overpass" }; }
function nearestMeters(coords, lat, lon) { let best = Infinity; const p = [lon, lat]; for (let i = 1; i < coords.length; i++) { const a = coords[i - 1], b = coords[i], dx = (b[0] - a[0]) * Math.cos(lat * Math.PI / 180), dy = b[1] - a[1], px = (p[0] - a[0]) * Math.cos(lat * Math.PI / 180), py = p[1] - a[1], den = dx * dx + dy * dy, t = den ? Math.max(0, Math.min(1, (px * dx + py * dy) / den)) : 0; best = Math.min(best, Math.hypot((px - t * dx) * 111320, (py - t * dy) * 111320)); } return best; }
function sourceUrl(x) { return x.id == null ? "" : `https://www.openstreetmap.org/${x.type}/${x.id}`; }

export async function discoverScenicStops(start, end, scenic = 50, signal) { const a = start?.lat != null ? [start.lon ?? start.lng, start.lat] : null, b = end?.lat != null ? [end.lon ?? end.lng, end.lat] : null; const coords = corridor([a, b].filter(Boolean)); if (coords.length < 2) return { status: "unavailable", stops: [], features: [] }; try { const payload = await fetchJson(getConfig().overpassBaseUrl, { method: "POST", body: `data=${encodeURIComponent(query(coords))}`, headers: { "Content-Type": "application/x-www-form-urlencoded" }, timeoutMs: getConfig().overpassTimeoutMs, signal }); const status = payload?.remark ? "partial" : "ready", base = normalize(payload, status); const stops = base.features.filter((x) => x.lat != null && x.lon != null && !/^(motorway|trunk)$/.test(String(x.tags.highway || "")) && x.tags.landuse !== "industrial" && x.tags.industrial == null).map((x) => { const tags = x.tags || {}, value = tags.tourism === "viewpoint" ? 30 : tags.natural === "water" || tags.waterway ? 25 : tags.natural === "wood" || tags.natural === "forest" || tags.landuse === "forest" ? 20 : tags.leisure === "park" ? 15 : tags.leisure === "nature_reserve" || tags.boundary === "protected_area" ? 25 : Number(scenic) || 10; return { name: tags.name || tags["name:zh"] || "自然景观", type: tags.tourism || tags.natural || tags.leisure || "scenic", note: tags.description || "", sourceUrl: sourceUrl(x), scenicValue: value, tags, lat: x.lat, lon: x.lon, source: "overpass" }; }); return { ...base, stops }; } catch (e) { return { status: statusFor(e, signal), stops: [], features: [], error: String(e?.message || e) }; } }
export async function queryRouteAmenities(route, signal) { const coords = corridor(routeCoordinates(route)); if (coords.length < 2 || coords.length > 12000) return { status: "unavailable", features: [], supplies: { status: "unavailable", items: [] } }; try { const config = getConfig(), elements = []; let partial = false; for (const batch of chunks(coords, 180)) { const payload = await fetchJson(config.overpassBaseUrl, { method: "POST", body: `data=${encodeURIComponent(query(batch, true))}`, headers: { "Content-Type": "application/x-www-form-urlencoded" }, timeoutMs: config.overpassTimeoutMs, signal }); if (payload?.remark) partial = true; if (Array.isArray(payload?.elements)) elements.push(...payload.elements); } const base = normalize({ elements }, partial ? "partial" : "ready"), seen = new Set(), items = []; for (const x of base.features) { const t = x.tags || {}; if (!(t.amenity && /^(cafe|restaurant|fuel)$/.test(t.amenity)) && !(t.shop && /^(convenience|supermarket)$/.test(t.shop))) continue; const d = x.lat == null ? Infinity : nearestMeters(coords, x.lat, x.lon); if (d > 500) continue; const key = `${x.type}:${x.id}`; if (seen.has(key)) continue; seen.add(key); items.push({ type: t.amenity || t.shop, name: t.name || t["name:zh"] || "补给点", lat: x.lat, lon: x.lon, distance: Math.round(d), distanceMeters: Math.round(d), distanceKm: Number((d / 1000).toFixed(3)), sourceUrl: sourceUrl(x) }); } return { ...base, supplies: { status: base.status, items }, routePoints: coords.length }; } catch (e) { const status = statusFor(e, signal); return { status, features: [], supplies: { status, items: [] }, error: String(e?.message || e) }; } }
export { safeElement };
